version: '3.3'

services:
  mysql:
    image: mysql:8.0
    container_name: better-banking
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=betterbanking
      - MYSQL_PASSWORD=betterbanking
      - MYSQL_USER=betterbanking
      - MYSQL_DATABASE=betterbanking
    volumes:
      - mysql-better-banking-data:/var/lib/mysql-better-banking-data
# Names our volume
volumes:
  mysql-better-banking-data: